---
title: "STAT/MATH 495: Problem Set 10"
author: "Wayne Maumbe"
date: "2017-11-28"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: false
    smooth_scroll: false
    df_print: kable
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=8, fig.height=4.5, message=FALSE, warning = FALSE)
```
 
 
 
# Collaboration
 
Please indicate who you collaborated with on this assignment:
 
 Meron Gedrago
 

 
```{r echo=FALSE}
library(tidyverse)
library(broom)
library(glmnet)
library(readr)
library(MLmetrics)
 
train <- read_csv("~/Advanced Data Analysis/Week 1/PS10/data/train.csv")
test <- read_csv("~/Advanced Data Analysis/Week 1/PS10/data/test.csv")
sample_submission <- read_csv("~/Advanced Data Analysis/Week 1/PS10/data/sample_submission.csv")
 
# Only use 150 observations to train model!
set.seed(76)
train <- train %>%
  mutate(log_price_doc = log(price_doc)) %>%
  sample_n(150)
 
# Need "dummy" outcome variable to make model.matrix() code below work
test <- test %>%
  mutate(log_price_doc=1)
 
# Model formula
model_formula <- as.formula("log_price_doc ~ full_sq + area_m + raion_popul + green_zone_part + indust_part + children_preschool + preschool_education_centers_raion + children_school + school_education_centers_raion + school_education_centers_top_20_raion + healthcare_centers_raion + university_top_20_raion + sport_objects_raion + additional_education_raion + culture_objects_top_25 + culture_objects_top_25_raion + shopping_centers_raion + office_raion + thermal_power_plant_raion + incineration_raion + oil_chemistry_raion + radiation_raion + railroad_terminal_raion + big_market_raion + nuclear_reactor_raion + detention_facility_raion + full_all + male_f + female_f + young_all + young_male + young_female + work_all + work_male + work_female + ekder_all + ekder_male + ekder_female + ID_metro + metro_min_avto + metro_km_avto + kindergarten_km + school_km + park_km + green_zone_km + industrial_km + water_treatment_km + cemetery_km + incineration_km + railroad_station_avto_km + railroad_station_avto_min + ID_railroad_station_avto + public_transport_station_km + public_transport_station_min_walk + water_km + water_1line + mkad_km + ttk_km + sadovoe_km + bulvar_ring_km + kremlin_km + big_road1_km + ID_big_road1 + big_road1_1line + big_road2_km + ID_big_road2 + railroad_km + railroad_1line + zd_vokzaly_avto_km + ID_railroad_terminal + bus_terminal_avto_km + ID_bus_terminal + oil_chemistry_km + nuclear_reactor_km + radiation_km + power_transmission_line_km + thermal_power_plant_km + ts_km + big_market_km + market_shop_km + fitness_km + swim_pool_km + ice_rink_km + stadium_km + basketball_km + hospice_morgue_km + detention_facility_km + public_healthcare_km + university_km + workplaces_km + shopping_centers_km + office_km + additional_education_km + preschool_km + big_church_km + church_synagogue_km + mosque_km + theater_km + museum_km + exhibition_km + catering_km + green_part_500 + prom_part_500 + office_count_500 + office_sqm_500 + trc_count_500 + trc_sqm_500")
 
# Define predictor matrices
predictor_matrix_train <- model.matrix(model_formula, data = train)[, -1]
predictor_matrix_test <- model.matrix(model_formula, data = test)[, -1]
```
 
 
# Do work and create submission files:
 
```{r}
#LASSO_CROSSVALIDATION
#  Define values of tuning/complexity parameter lambda

lambda_inputs <- 10^seq(-2, 10, length = 100)
 
# Fit the model using glmnet

LASSO_CV <- cv.glmnet(x=predictor_matrix_train, y=train$log_price_doc, alpha=1, lambda=lambda_inputs)
lambda_star_1SE <- LASSO_CV$lambda.1se
y_hat<-predict(LASSO_CV, newx=predictor_matrix_train, s=lambda_star_1SE) %>%
  as_tibble()
y_hat<-exp(y_hat)
mse1<-RMSLE(y_hat, train$price_doc)

 
#LASSO_PREDICTIVE MODEL
LASSO_fit <- glmnet(x=predictor_matrix_train, y=train$log_price_doc, alpha = 1, lambda = lambda_inputs)
y_hat <- predict(LASSO_fit, newx=predictor_matrix_test, s=lambda_star_1SE) %>%
  as_tibble()
y_hat<-exp(y_hat)
id<-as.data.frame(test$id) 
sample_submission<-cbind(id,price_doc=y_hat)
colnames(sample_submission)[1]<-"id"
colnames(sample_submission)[2]<-"price_doc"
write_csv(sample_submission, "submission1.csv")

#lm
LM_CV<-lm(model_formula, cv=TRUE, data=train)
y_hat <- predict(LM_CV, newdata=test) %>%
  as_tibble()
y_hat<-exp(y_hat)
mse2<-RMSLE(y_hat, train$price_doc)


#lm_predictive model
LM_fit<-lm(model_formula, data = train)
y_hat <- predict(LM_fit, newdata=test) %>%
  as_tibble()
y_hat<-exp(y_hat)
id<-as.data.frame(test$id) 
sample_submission<-cbind(id,price_doc=y_hat)
colnames(sample_submission)[1]<-"id"
colnames(sample_submission)[2]<-"price_doc"
write_csv(sample_submission, "submission2.csv")

```
 
 
 
 
 
# Scoreboard
 
Using the "scoring mechanism" for the Russian Housing Kaggle competition, fill
in these cells:
 
 
Method                | Training Score  | Kaggle Score
--------------------- | -------------   | -------------
lm                    |    `r mse2`     | 2.63413
LASSO crossvalidated  |    `r mse1`     | 0.42577